name: jungle
channels:
  - etetoolkit
  - bpteague
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - biopython=1.74
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - enum34=1.1.6
  - ete3=3.1.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - functools32=3.2.3.2
  - futures=3.3.0
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.0
  - ipykernel=4.10.0
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jpeg=9b
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.1
  - matplotlib=2.2.3
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1d
  - pandas=0.24.2
  - pathlib2=2.3.5
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=2.7.17
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - readline=7.0
  - scandir=1.10.0
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.4.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.31.1
  - statsmodels=0.10.1
  - subprocess32=3.5.4
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11